#Requires AutoHotkey v2.0

#Include generated/Allowlists.ahk
#Include generated/GuiComponentType.ahk
#Include core/SapHookPolicy.ahk
#Include core/SapTypeRegistry.ahk
#Include core/SapComProxy.ahk
#Include core/SapCollectionProxy.ahk
#Include core/SapGuiBootstrap.ahk

#Include types/GuiComponent.ahk
#Include types/GuiContainer.ahk
#Include types/GuiVContainer.ahk
#Include types/GuiShell.ahk
#Include types/GuiAbapEditor.ahk
#Include types/GuiApoGrid.ahk
#Include types/GuiApplication.ahk
#Include types/GuiBarChart.ahk
#Include types/GuiVComponent.ahk
#Include types/GuiBox.ahk
#Include types/GuiButton.ahk
#Include types/GuiCTextField.ahk
#Include types/GuiCalendar.ahk
#Include types/GuiChart.ahk
#Include types/GuiCheckBox.ahk
#Include types/GuiCollection.ahk
#Include types/GuiColorSelector.ahk
#Include types/GuiComboBox.ahk
#Include types/GuiComboBoxControl.ahk
#Include types/GuiComboBoxEntry.ahk
#Include types/GuiComponentCollection.ahk
#Include types/GuiConnection.ahk
#Include types/GuiContainerShell.ahk
#Include types/GuiMenu.ahk
#Include types/GuiContextMenu.ahk
#Include types/GuiCustomControl.ahk
#Include types/GuiDialogShell.ahk
#Include types/GuiEAIViewer2D.ahk
#Include types/GuiEAIViewer3D.ahk
#Include types/GuiEnum.ahk
#Include types/GuiFrameWindow.ahk
#Include types/GuiGOSShell.ahk
#Include types/GuiGraphAdapt.ahk
#Include types/GuiGridView.ahk
#Include types/GuiHTMLViewer.ahk
#Include types/GuiInputFieldControl.ahk
#Include types/GuiLabel.ahk
#Include types/GuiMainWindow.ahk
#Include types/GuiMap.ahk
#Include types/GuiMenubar.ahk
#Include types/GuiMessageWindow.ahk
#Include types/GuiModalWindow.ahk
#Include types/GuiNetChart.ahk
#Include types/GuiOfficeIntegration.ahk
#Include types/GuiOkCodeField.ahk
#Include types/GuiPasswordField.ahk
#Include types/GuiPicture.ahk
#Include types/GuiRadioButton.ahk
#Include types/GuiSapChart.ahk
#Include types/GuiScrollContainer.ahk
#Include types/GuiScrollbar.ahk
#Include types/GuiSession.ahk
#Include types/GuiSessionInfo.ahk
#Include types/GuiSimpleContainer.ahk
#Include types/GuiSplit.ahk
#Include types/GuiSplitterContainer.ahk
#Include types/GuiStage.ahk
#Include types/GuiStatusPane.ahk
#Include types/GuiStatusbar.ahk
#Include types/GuiTab.ahk
#Include types/GuiTabStrip.ahk
#Include types/GuiTableColumn.ahk
#Include types/GuiTableControl.ahk
#Include types/GuiTableRow.ahk
#Include types/GuiTextedit.ahk
#Include types/GuiTitlebar.ahk
#Include types/GuiToolbar.ahk
#Include types/GuiTree.ahk
#Include types/GuiUserArea.ahk
#Include types/GuiUtils.ahk
#Include types/GuiVHViewSwitch.ahk
